encoding = {
    "ib5b": "5 Year History-Board and care home, assisted living",
    "ib5a": "5 Year History-Long Term Care Facility",
    "ib5e": "5 Year History-Mental health residence psychiatric group home",
    "ib5d": "5 Year History-Setting for persons with intellectual disability",
    "id4a": "Ability to see in adequate light (with glasses or with other visual appliance normally used)",
    "id2": "Ability to understand others",
    "ij2g": "Abnormal thought process loosening of associations, blocking, flight of ideas, tangentiality, circumstantiality",
    "cabuse": "Abusive Relationship CAP",
    "iq3b": "Accessibility to grocery store without assistance",
    "ij2m": "Acid reflux Regurgitation of acid from stomach to throat",
    "cactiv": "Activities CAP",
    "ic4": "Acute change in Mental Status from persons usual functioning",
    "im3": "Adherent with any medication prescribed by physician",
    "cadl": "ADL CAP",
    "ip1d1": "ADL care - by person 1",
    "ip1d2": "ADL care - by person 2",
    "sadllf": "ADL Long Form Scale 0-28 range",
    "sadlsf": "ADL Short Form Scale 0-16 range",
    "ig2a": "ADL: Bathing",
    "ig2i": "ADL: Bed mobility",
    "ig2d": "ADL: Dressing lower body",
    "ig2c": "ADL: Dressing upper body",
    "ig2j": "ADL: Eating",
    "ig2f": "ADL: Locomotion",
    "ig2b": "ADL: Personal hygiene",
    "ig2h": "ADL: Toilet use",
    "ig2g": "ADL: Transfer toilet",
    "ig2e": "ADL: Walking",
    "age_cat": "Age categories",
    "ia3": "Age of patient at assessment (years)",
    "ij8b": "Alcohol: Highest number of drinks in any single sitting in last 14 days",
    "im2": "Allergy to any drug",
    "ii1c": "Alzheimers disease",
    "ii1n": "Anxiety",
    "ij2j": "Aphasia",
    "cdrug": "Appropriate Medications CAP",
    "ia12b": "As compared to 90 days ago, person now lives with someone new",
    "ij2t": "Aspiration",
    "ia9": "Assessment reference date",
    "iu1": "Assessment signed as complete",
    "aaxurg": "Assessment Urgency Algorithm 1 least to 6 most-Hirdes",
    "ibenc_wave": "assessment wave",
    "iq3a": "Availability of emergency assistance",
    "iq3c": "Availability of home delivery of groceries",
    "ig9b": "Awareness of suggestions that person limits or stops driving",
    "cbehav": "Behavior CAP",
    "ii1w": "Bipolar disorder",
    "ih1": "Bladder continence",
    "in1d": "Blood pressure measured in past year",
    "ik4e": "BMI",
    "sbmi": "Body Mass Index (kg/m^2)",
    "cbowel": "Bowel CAP",
    "ih3": "Bowel continence",
    "ij5d": "Breakthrough pain",
    "cbritsu": "Brittle Support CAP",
    "ii1s": "Cancer",
    "ccardio": "Cardio-respiratory CAP",
    "ig8a": "Change in ADL status as compared to 90 days ago, or since last assessment",
    "ic5": "Change in Decision Making as compared to 90 days ago",
    "if2": "Change in social activities in last 90 days or since last assesment, if less than 90 days ago",
    "ij2e": "Chest pain",
    "ii1m": "Chronic obstructive pulmonary disease COPD",
    "cmi": "CMI case mix index-formal Bjorkgren 2000",
    "cmi_poss": "CMI case mix index-formal Poss 2014",
    "cmifi": "CMIFI case mix index-formal and informal Bjorkgren 2000",
    "cmifi_poss": "CMIFI case mix index-formal and informal Poss 2014",
    "ccognit": "Cognitive CAP",
    "ic1": "Cognitive Skills for Daily Decision Making",
    "in1h": "Colonoscopy in past 5 years",
    "ccommun": "Communication CAP",
    "ij6a": "Conditions diseases make cognitive, ADL, mood, or behavior patterns unstable",
    "if1e": "Conflict or anger with family or friends",
    "ii1l": "Congestive heart failure CHF",
    "ij5c": "Consistency of pain",
    "ij2k": "Constipation No bowel movement in 3 days or difficult passage of hard stool",
    "ii1k": "Coronary heart disease",
    "cc": "Country code",
    "cps2": "CPS Version 2 -0-8 range-includes milder impairment stages-Morris 2014",
    "ie1g": "Crying, tearfulness",
    "iu2": "Date assessment signed as complete",
    "sdbsi": "Deafblind Severity Index 0-5 range",
    "ik2b": "Dehydrated or BUN Cre ratio > 25",
    "cdehyd": "Dehydration CAP",
    "cdelir": "Delirium CAP",
    "ij2h": "Delusions Fixed false beliefs",
    "ii1d": "Dementia other than Alzheimers disease",
    "in1e": "Dental exam in past year",
    "ii1o": "Depression",
    "ii1t": "Diabetes mellitus",
    "ij2l": "Diarrhea",
    "ij2a": "Difficult or unable to move self to standing position unassisted",
    "ij2b": "Difficult or unable to turn self around and face the opposite direction when standing",
    "ij2f": "Difficulty clearing airway secretions",
    "ij2o": "Difficulty falling asleep or staying asleep waking up too early restlessness non-restful sleep",
    "ia8discharge": "discharged?",
    "ii2na": "Disease code",
    "ii2oa": "Disease code",
    "iq1a": "Disrepair of the Home",
    "ig4": "Distance walked",
    "ig5": "Distance wheeled",
    "ij2c": "Dizziness",
    "ig9a": "Drove car vehicle in the last 90 days",
    "ij3": "Dyspnea: Shortness of breath",
    "sedmonton": "Edmonton Frailty Scale 4 Categories",
    "in5b": "Emercency room visit (not counting overnight stay): # times past 90 days",
    "ij6c": "End-stage disease, 6 or fewer months to live",
    "cenvir": "Environmental CAP",
    "ib3": "Ethnicity and race",
    "ij6b": "Experiencing an acute episode, or a flare-up of a recurrent or chronic problem",
    "ie1k": "Expressions, including nonverbal, of a lack of pleasure in life (anhedonia)",
    "ie1c": "Expressions, including nonverbal, of what appear to be unrealistic fears",
    "in1g": "Eye exam  in past year",
    "ij1": "Falls",
    "cfalls": "Falls CAP",
    "if7d": "Family overwhelmed",
    "ij4": "Fatigue",
    "if1f": "Fearful of a family member or close acquaintance",
    "cfeedtb": "Feeding Tube CAP",
    "ij2q": "Fever Aspiration",
    "sfi_corrected_long": "FI_frailty index_long-44 items-Searle_Armstrong_specs",
    "iq4": "Finances: because of limited funds made trade-offs the last 30 days",
    "ik2c": "Fluid intake less than 1000cc per day",
    "ik2h": "Fluid output exceeds input",
    "il7": "Foot problems, eg bunions, hammertoes, overlapping toes, structural problems, infections, ulcers",
    "ij5a": "Frequency with which person complains or shows evidence of pain",
    "sfried_brtotal": "Fried_Frailty Criteria Bandeen-Roche specs (0-5) v1",
    "ia2": "Gender",
    "sgerscr": "Geriatric Screener 0-1 range",
    "ij2r": "GI or GU bleeding",
    "ij2i": "Hallucinations False sensory perceptions",
    "iq2": "Handicapped re-engineered apartment accessible for persons with disabilities",
    "ik4b": "Has broken, fragmented, loose, or otherwise non-intact natural teeth",
    "in1f": "Hearing exam in past year",
    "id3a": "Hearing: ability to hear (with hearing appliance normally used)",
    "ii1e": "Hemiplegia",
    "ii1a": "Hip fracture during last 30 days",
    "in3aa": "Home health aides - # days in past 7 days",
    "in3ab": "Home health aides - total minutes in past week",
    "in3ba": "Home nurse - # days in past 7 days",
    "in3bb": "Home nurse - total minutes in past week",
    "in3ca": "Homemaking services - # days in past 7 days",
    "in3cb": "Homemaking services - total minutes in past week",
    "ip3": "Hours of informal care and active monitoring during last 3 days: #",
    "ij2mm": "Hygiene Unusually poor hygiene, unkempt, disheveled",
    "siadlch": "IADL Capacity Hierarchy Scale 0-6 range",
    "siadlc": "IADL Capacity scale 0-48 range",
    "ip1c1": "IADL care -  by person 1",
    "ip1c2": "IADL care - by person 2",
    "ciadl": "IADL Improvement CAP",
    "siadlp": "IADL Performance scale 0-48 range",
    "ig1cb": "IADL: Managing finances   Capacity",
    "ig1ca": "IADL: Managing finances Performance",
    "ig1db": "IADL: Managing medications   Capacity",
    "ig1da": "IADL: Managing medications   Performance",
    "ig1ab": "IADL: Meal preparation  Capacity",
    "ig1aa": "IADL: Meal preparation  Performance",
    "ig1bb": "IADL: Ordinary housework    Capacity",
    "ig1ba": "IADL: Ordinary housework    Performance",
    "ig1ea": "IADL: Phone use   performance",
    "ig1eb": "IADL: Phone use  Capacity",
    "ig1ga": "IADL: Shopping   performance",
    "ig1gb": "IADL: Shopping  Capacity",
    "ig1fb": "IADL: Stairs  Capacity",
    "ig1fa": "IADL: Stairs  performance",
    "ig1hb": "IADL: Transportation  Capacity",
    "ig1ha": "IADL: Transportation performance",
    "org_no": "IBenC organisation number",
    "ii2ebb": "ICD10 code",
    "id": "ID Inspire 2018",
    "ig6b": "In the last 3 days: nr of days went out  house or building in which he or she resides",
    "ie2b": "In the past 3 days: Anxious, restless, or uneasy?",
    "ie2a": "In the past 3 days: Little interest or pleasure in things you normally enjoy?",
    "ie2c": "In the past 3 days: Sad, depressed, or hopeless?",
    "iq1c": "Inadequate heating or cooling",
    "ie3f": "Inappropriate public sexual behavior or public disrobing",
    "in1a": "Influenza vaccine  in past 2 years",
    "ip1a1": "Informal help-relationship - 1",
    "ip1a2": "Informal help-relationship - 2",
    "ip2a": "Informal helper(s) is/are unable to continue in caring activities",
    "in5a": "Inpatient acute hospital with overnight stay: # times past 90 days",
    "crisk": "Institutional risk CAP",
    "ij5b": "Intensity of highest level of pain present",
    "iq1d": "Lack of personal safety",
    "it1": "Last day of stay",
    "io1a": "legal gardian present",
    "if3": "Lenght of the time alone during the day (morning and evening)",
    "iq1e": "Limited access to home  or rooms in home",
    "ip1b1": "Lives with person - 1",
    "ip1b2": "Lives with person - 2",
    "ia12a": "Living arrangement",
    "if1d": "Loneliness: indicates feelings of loneliness",
    "ie1a": "Made negative statements",
    "if4": "Major life stressors in last  last 90 days",
    "il4": "Major skin problems, eg lesions, 2nd- or 3rd degree burns, healing surgical wounds",
    "id1": "Making self understood",
    "in1c": "Mammogram or breast exam in past 2 years",
    "ia4": "Marital Status",
    "in3da": "Meals - # days in past 7 days",
    "ic2b": "Memory Recall Ability: Procedural Memory ok",
    "ic2a": "Memory Recall Ability: Short-term Memory ok",
    "ic2c": "Memory Recall Ability: Situational memory ok",
    "ik3": "Mode of nutritional intake",
    "cmood": "Mood CAP",
    "il1": "Most severe pressure ulcer",
    "ii1f": "Multiple sclerosis",
    "if1g": "Neglected, abused, or mistreated",
    "ir3": "Number of 10 Independent ADL  in which person was independent prior to detoriation: #",
    "ir4": "Number of 8 IADL performance areas in which person was independent prior to detoriation: #",
    "cnutr": "Nutrition CAP",
    "in3fa": "Occupational therapy - # days in past 7 days",
    "in3fb": "Occupational therapy - total minutes in past week",
    "ir1": "One or more care goals met in the last 90 days or since last assesment <90 days",
    "ir5": "Onset of precipitating event related to detoriation",
    "ii1b": "Other fracture during last 30 days",
    "if1c": "Other interaction with long-standing social relation or family member eg telephone e-mail",
    "il6": "Other skin condition or changes in skin condition, eg bruises, raches, itching, herpes zoster, intertrigo, eczema",
    "il3": "Other skin ulcer, eg  venous ulcer, arteriiL ulcer, mixed venous arterial ulcer, diabetic foot ulcer",
    "ir2": "Overall Self suffiency has changed significantly as compared to status 90 days ago",
    "ih4": "Pads or briefs worn",
    "cpain": "Pain CAP",
    "ij5e": "Pain control",
    "ii1g": "Paraplegia",
    "ii1h": "Parkinsons disease",
    "if1a": "Participation in social activities of long-standing interest",
    "in2m": "Past 3 days:  Palliative care program",
    "in2i": "Past 3 days:  Transfusion",
    "in2a": "Past 3 days: Chemotherapy",
    "in2b": "Past 3 days: Dialysis",
    "in2c": "Past 3 days: Infection control segregation",
    "in2d": "Past 3 days: IV Medication",
    "in2f": "Past 3 days: Radiation",
    "in2l": "Past 3 days: Scheduled toileting program",
    "in2g": "Past 3 days: Suctioning",
    "in2h": "Past 3 days: Tracheostomy care",
    "in2n": "Past 3 days: Turning program",
    "in2j": "Past 3 days: Ventilator",
    "in2k": "Past 3 days: Wound care",
    "in2e": "Past 3 days:Oxygen therapy",
    "ic3a": "Periodic disordered thinking or awareness: Easily Distracted",
    "ic3b": "Periodic disordered thinking or awareness: Episodes of Disorganized Speech",
    "ic3c": "Periodic disordered thinking or awareness: Mental function varies over the course of the day",
    "ij2s": "Peripheral edema",
    "ie1b": "Persistent anger with self or others",
    "ia12c": "Person or relative feels that the person would be better off living elsewhere",
    "spsi": "Personal Severity Index 0-28 Morris",
    "ie3c": "Physical abuse, others were hit, shoved, scratched, sexually abused",
    "cpactiv": "Physical Activity Promotion CAP",
    "ig7b": "Physical function improvement potential: Caregiver believes can improve",
    "ig7a": "Physical function improvement potential: Person believes can improve",
    "in3ea": "Physical therapy - # days in past 7 days",
    "in3eb": "Physical therapy - total minutes in past week",
    "in4": "Physically restrained",
    "in5c": "Physician visit (or autorized assistant or practioner): # times past 90 days",
    "ii1q": "Pneumonia",
    "in1b": "Pneumovaxx vaccine in past 5 years or after 65 years",
    "cpulcer": "Pressure Ulcer CAP",
    "cpreven": "Prevention CAP",
    "cpreven_nl": "Prevention CAP aangepast NL (zonder colonsc, pneumovaxx)",
    "ip2b": "Primary Informal helper expresses feelings of distress, anger or depression",
    "ib4": "Primary language",
    "ig3": "Primary mode of locomotion",
    "il2": "Prior pressure ulcer",
    "in3ha": "Psychological therapies - # days in past 7 days",
    "in3hb": "Psychological therapies - total minutes in past week",
    "ii1i": "Quadriplegia",
    "ia8": "Reason for assessment",
    "ia8r": "reason for assessment",
    "ij12": "Recent falls",
    "ie1h": "Recurrent statements that something terrible is about to happen",
    "ie1j": "Reduced social interactions",
    "arehab": "Rehabilitation Algorithm-Hirdes",
    "ie1e": "Repetitive anxious complaints or concerns (non-health related)",
    "ie1d": "Repetitive health complaints",
    "ik4c": "Reports difficulty chewing",
    "ik4d": "Reports dry mouth",
    "ia11b": "Residential / living status at time of assessment",
    "it2": "Residential or living status after discharge",
    "ie3e": "Resists care, taking medications, injections, ADL assistance, eating",
    "rughclin": "RUG HC Clinical Group",
    "ar3h": "RUGIIIHC Clinical (sub)group",
    "rugiiihc": "RUGIIIHC Clinical (sub)group",
    "sabs": "sABS Aggressive Behaviour Scale 0-12 range =0 no 1-4 mild to moderate 5+more severe",
    "ie1f": "Sad, pained, or worried facial expressions",
    "sadlh": "sADLH ADL hierarchy scale (0-6)",
    "schess": "sCHESS (range 0-5): Changes in Health, End-stage disease, Signs and Symptoms Scale",
    "ii1p": "Schizophrenia",
    "scps": "sCPS Cognitive Performance Scale 0-6 range-Morris 1991",
    "scps2": "sCPS2 scale 0-6 range - includes procedural Memory item",
    "sdivert": "sDIVERT Scale  1-6 range",
    "sdrs": "sDRS depression rating scale (0-14)",
    "ij7": "Self reported health",
    "asri": "Self-reliance Index for HC",
    "aservurg": "Service Urgency Algorithm 1 lowest to 4 highest-Hirdes",
    "il5": "Skin tears or cuts other than surgery",
    "smaple": "sMAPLE Algorithm 0-5 range",
    "ij8a": "Smokes tobacco daily",
    "cadd": "Smoking and Drinking CAP",
    "csocfunc": "Social Function CAP",
    "ie3d": "Socially inappropriate or disruptive behavior",
    "in3ga": "Speech therapy - # days in past 7 days",
    "in3gb": "Speech therapy - total minutes in past week",
    "spurs": "sPURS- Pressure Ulcer Risk Scale (sPURS) 0-8 range",
    "iq1b": "Squalid condition",
    "srise_hc": "sRISE: Revised index social engagement for HC",
    "ii1j": "Stroke CVA",
    "if8a": "strong relationship with family",
    "ia13": "Time since last hospital stay",
    "ig12": "Timed walk",
    "ij2p": "Too much sleep, excessive amount of sleep that interferes with person's normal functioning",
    "ig6a": "Total hours of exercise or physical activity in last 3 days",
    "ij2d": "Unsteady gait",
    "ih2": "Urinary collection device (exclude pads or briefs)",
    "curin": "Urinary Incontinence CAP",
    "ii1r": "Urinary tract infection in last 30 days",
    "ie3b": "Verbal abuse, others were threatened, screamed at, cursed at",
    "if1b": "Visit with a long-standing social relation or family member",
    "ij2n": "Vomiting",
    "ie3a": "Wandering, moved with no rational purpose, seemingly oblivious to needs or safety",
    "ik4a": "Wears a denture (removable prothesis)",
    "ik2a": "Weight loss of more than 5% in the last 30 days, or 10% or more in the last 180 days",
    "ie1i": "Withdrawal from activities of interest",
}
